# Generated by Django 3.0.5 on 2020-04-04 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_str', models.TextField()),
                ('tweet', models.TextField(blank=True, null=True)),
                ('conversation_id', models.TextField()),
                ('created_at', models.BigIntegerField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('timezone', models.TextField()),
                ('place', models.TextField(blank=True, null=True)),
                ('replies_count', models.IntegerField(blank=True, null=True)),
                ('likes_count', models.IntegerField(blank=True, null=True)),
                ('retweets_count', models.IntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField()),
                ('user_id_str', models.TextField()),
                ('screen_name', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('mentions', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('cashtags', models.TextField(blank=True, null=True)),
                ('urls', models.TextField(blank=True, null=True)),
                ('photos', models.TextField(blank=True, null=True)),
                ('quote_url', models.TextField(blank=True, null=True)),
                ('video', models.IntegerField(blank=True, null=True)),
                ('geo', models.TextField(blank=True, null=True)),
                ('near', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('time_update', models.BigIntegerField()),
                ('translate', models.TextField(blank=True, null=True)),
                ('trans_src', models.TextField(blank=True, null=True)),
                ('trans_dest', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter_Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_platform', models.TextField(max_length=100)),
                ('target_type', models.TextField(max_length=100)),
                ('twitter_username', models.TextField(max_length=100)),
                ('submission_date', models.TextField(max_length=100)),
                ('target_scheduling', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_str', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('username', models.TextField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('join_date', models.TextField()),
                ('join_time', models.TextField()),
                ('tweets', models.IntegerField(blank=True, null=True)),
                ('following', models.IntegerField(blank=True, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('media', models.IntegerField(blank=True, null=True)),
                ('private', models.IntegerField()),
                ('verified', models.IntegerField()),
                ('profile_image_url', models.TextField()),
                ('background_image', models.TextField(blank=True, null=True)),
                ('hex_dig', models.TextField()),
                ('time_update', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='twitter.Users')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='twitter.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='twitter.Users')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='twitter.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='twitter.Users')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='twitter.Tweets')),
            ],
        ),
    ]
