# Generated by Django 3.0.5 on 2020-04-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20200406_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_target',
            name='scanning_status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
