# Generated by Django 3.0.5 on 2020-04-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_followingnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='twitter.Tweets')),
            ],
        ),
    ]
