# Generated by Django 3.0.5 on 2020-04-04 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_replies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retweets',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='twitter.Users')),
                ('username', models.TextField()),
                ('retweet_id', models.BigIntegerField()),
                ('retweet_date', models.BigIntegerField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='twitter.Tweets')),
            ],
        ),
    ]
