# Generated by Django 3.0.5 on 2020-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20200406_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitter_target',
            name='id',
        ),
        migrations.AlterField(
            model_name='twitter_target',
            name='target_platform',
            field=models.CharField(default='twitter', max_length=255),
        ),
        migrations.AlterField(
            model_name='twitter_target',
            name='twitter_username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
